export const crossViaTableData = [
	{
		base: "AUD",
		items: [
			{ term: "AUD", crossvia: "1" },
			{ term: "CAD", crossvia: "USD" },
			{ term: "CNY", crossvia: "USD" },
			{ term: "CZK", crossvia: "USD" },
			{ term: "DKK", crossvia: "USD" },
			{ term: "EUR", crossvia: "USD" },
			{ term: "GBP", crossvia: "USD" },
			{ term: "JPY", crossvia: "USD" },
			{ term: "NOK", crossvia: "USD" },
			{ term: "NZD", crossvia: "USD" },
			{ term: "USD", crossvia: "D" },
		],
	},
	{
		base: "CAD",
		items: [
			{ term: "AUD", crossvia: "USD" },
			{ term: "CAD", crossvia: "1" },
			{ term: "CNY", crossvia: "USD" },
			{ term: "CZK", crossvia: "USD" },
			{ term: "DKK", crossvia: "USD" },
			{ term: "EUR", crossvia: "USD" },
			{ term: "GBP", crossvia: "USD" },
			{ term: "JPY", crossvia: "USD" },
			{ term: "NOK", crossvia: "USD" },
			{ term: "NZD", crossvia: "USD" },
			{ term: "USD", crossvia: "D" },
		],
	},
	{
		base: "CNY",
		items: [
			{ term: "AUD", crossvia: "USD" },
			{ term: "CAD", crossvia: "USD" },
			{ term: "CNY", crossvia: "1" },
			{ term: "CZK", crossvia: "USD" },
			{ term: "DKK", crossvia: "USD" },
			{ term: "EUR", crossvia: "USD" },
			{ term: "GBP", crossvia: "USD" },
			{ term: "JPY", crossvia: "USD" },
			{ term: "NOK", crossvia: "USD" },
			{ term: "NZD", crossvia: "USD" },
			{ term: "USD", crossvia: "D" },
		],
	},
	{
		base: "CZK",
		items: [
			{ term: "AUD", crossvia: "USD" },
			{ term: "CAD", crossvia: "USD" },
			{ term: "CNY", crossvia: "USD" },
			{ term: "CZK", crossvia: "1" },
			{ term: "DKK", crossvia: "EUR" },
			{ term: "EUR", crossvia: "Inv" },
			{ term: "GBP", crossvia: "USD" },
			{ term: "JPY", crossvia: "USD" },
			{ term: "NOK", crossvia: "EUR" },
			{ term: "NZD", crossvia: "USD" },
			{ term: "USD", crossvia: "EUR" },
		],
	},
	{
		base: "DKK",
		items: [
			{ term: "AUD", crossvia: "USD" },
			{ term: "CAD", crossvia: "USD" },
			{ term: "CNY", crossvia: "USD" },
			{ term: "CZK", crossvia: "EUR" },
			{ term: "DKK", crossvia: "1" },
			{ term: "EUR", crossvia: "Inv" },
			{ term: "GBP", crossvia: "USD" },
			{ term: "JPY", crossvia: "USD" },
			{ term: "NOK", crossvia: "EUR" },
			{ term: "NZD", crossvia: "USD" },
			{ term: "USD", crossvia: "EUR" },
		],
	},
	{
		base: "EUR",
		items: [
			{ term: "AUD", crossvia: "USD" },
			{ term: "CAD", crossvia: "USD" },
			{ term: "CNY", crossvia: "USD" },
			{ term: "CZK", crossvia: "D" },
			{ term: "DKK", crossvia: "D" },
			{ term: "EUR", crossvia: "1" },
			{ term: "GBP", crossvia: "USD" },
			{ term: "JPY", crossvia: "USD" },
			{ term: "NOK", crossvia: "D" },
			{ term: "NZD", crossvia: "USD" },
			{ term: "USD", crossvia: "D" },
		],
	},
	{
		base: "GBP",
		items: [
			{ term: "AUD", crossvia: "USD" },
			{ term: "CAD", crossvia: "USD" },
			{ term: "CNY", crossvia: "USD" },
			{ term: "CZK", crossvia: "USD" },
			{ term: "DKK", crossvia: "USD" },
			{ term: "EUR", crossvia: "USD" },
			{ term: "GBP", crossvia: "1" },
			{ term: "JPY", crossvia: "USD" },
			{ term: "NOK", crossvia: "USD" },
			{ term: "NZD", crossvia: "USD" },
			{ term: "USD", crossvia: "D" },
		],
	},
	{
		base: "JPY",
		items: [
			{ term: "AUD", crossvia: "USD" },
			{ term: "CAD", crossvia: "USD" },
			{ term: "CNY", crossvia: "USD" },
			{ term: "CZK", crossvia: "USD" },
			{ term: "DKK", crossvia: "USD" },
			{ term: "EUR", crossvia: "USD" },
			{ term: "GBP", crossvia: "USD" },
			{ term: "JPY", crossvia: "1" },
			{ term: "NOK", crossvia: "USD" },
			{ term: "NZD", crossvia: "USD" },
			{ term: "USD", crossvia: "Inv" },
		],
	},
	{
		base: "NOK",
		items: [
			{ term: "AUD", crossvia: "USD" },
			{ term: "CAD", crossvia: "USD" },
			{ term: "CNY", crossvia: "USD" },
			{ term: "CZK", crossvia: "EUR" },
			{ term: "DKK", crossvia: "EUR" },
			{ term: "EUR", crossvia: "Inv" },
			{ term: "GBP", crossvia: "USD" },
			{ term: "JPY", crossvia: "USD" },
			{ term: "NOK", crossvia: "1" },
			{ term: "NZD", crossvia: "USD" },
			{ term: "USD", crossvia: "EUR" },
		],
	},
	{
		base: "NZD",
		items: [
			{ term: "AUD", crossvia: "USD" },
			{ term: "CAD", crossvia: "USD" },
			{ term: "CNY", crossvia: "USD" },
			{ term: "CZK", crossvia: "USD" },
			{ term: "DKK", crossvia: "USD" },
			{ term: "EUR", crossvia: "USD" },
			{ term: "GBP", crossvia: "USD" },
			{ term: "JPY", crossvia: "USD" },
			{ term: "NOK", crossvia: "USD" },
			{ term: "NZD", crossvia: "1" },
			{ term: "USD", crossvia: "D" },
		],
	},
	{
		base: "USD",
		items: [
			{ term: "AUD", crossvia: "Inv" },
			{ term: "CAD", crossvia: "Inv" },
			{ term: "CNY", crossvia: "Inv" },
			{ term: "CZK", crossvia: "EUR" },
			{ term: "DKK", crossvia: "EUR" },
			{ term: "EUR", crossvia: "Inv" },
			{ term: "GBP", crossvia: "Inv" },
			{ term: "JPY", crossvia: "D" },
			{ term: "NOK", crossvia: "EUR" },
			{ term: "NZD", crossvia: "Inv" },
			{ term: "USD", crossvia: "1" },
		],
	},
];
